version: "2"
run:
  concurrency: 8
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    cyclop:
      max-complexity: 10
      package-average: 0
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 60
      statements: 40
    gocritic:
      disabled-checks:
        - commentFormatting
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: false
    lll:
      line-length: 160
      tab-width: 1
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - lll
    staticcheck:
      checks:
        - '*'
      initialisms: ["GRPC", "TTL", "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: 'G115: integer overflow conversion'
      - linters:
          - govet
        text: 'shadow: declaration of "ctx" shadows declaration'
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 30
  max-same-issues: 20
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - prefix(golang.org)
        - prefix(github.com)
        - default
        - prefix(github.com/mikhailv)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
