addr: '0.0.0.0:5333'
http_addr: '' # if empty the same value as `addr` will be used

history:
  log_size: 2000
  dns_query_size: 2000

agent:
  base_url: 'http://127.0.0.1:5332/'
  timeout: 10s

dns:
  ttl_override: 60s
  drop_ech: false
  providers: {}

mdns:
  enabled: false
  services: []

storage:
  local:
    file: dns_store.dat
    save_interval: 10m

routing:
  rule:
    table: 1001
    priority: 1995
  reconcile:
    interval: 2m
    timeout: 20s
  route_timeout: 30m
  hosts: []
  static: []
