addr: '0.0.0.0:5333'
http_addr: '' # if empty the same value as `addr` will be used

logging:
  debug: false
  history_size: 2000

agent:
  base_url: 'http://127.0.0.1:5332/'
  timeout: 10s

dns:
  ttl_override: 60s
  drop_ech: false
  drop_aaaa: false
  query_history_size: 2000
  providers: {}

mdns:
  enabled: false
  services: []

storage:
  local:
    file: dns_store.dat
    save_interval: 10m

routing:
  table: 1001
  rules: []
  reconcile:
    interval: 2m
    timeout: 20s
  route_timeout: 30m
  hosts: []
  static: []

conntrack:
  poll_interval: 5s
  bucket_interval: 1m
  chunk_interval: 1h
  cache_duration: 3h
  save_interval: 10m
  data_dir: conntrack
  history_size: 1000
