addr: '0.0.0.0:5333'
http_addr: '' # if empty the same value as `addr` will be used

log_history_size: 2000
dns_query_history_size: 2000

agent_base_url: 'http://127.0.0.1:5332/api/'
agent_timeout: 10s

dns_provider: https://1.1.1.1/dns-query
#dns_provider: 1.1.1.1:53
dns_provider_timeout: 20s
dns_ttl_override: 60s

reconcile_interval: 2m
reconcile_timeout: 20s

mdns:
  domains: [local]
  addr: '224.0.0.0:5353'
  query_timeout: 500ms

dump:
  file: domains.json
  interval: 10m

routing:
  rule:
    table: 1001
    iif: br0
    priority: 1995
  route_timeout: 60m
