.PHONY: build
build:
	pnpm run build

.PHONY: watch
watch:
	pnpm run watch

.PHONY: serve
serve:
	pnpm run serve

.PHONY: lint
lint:
	pnpm run check
	pnpm run lint

.PHONY: format
format:
	pnpm run format
