addr: '0.0.0.0:5333'

#dns_provider: https://1.1.1.1/dns-query
dns_provider: 1.1.1.1:53
dns_provider_timeout: 20m

reconcile_interval: 5m

dump:
  file: domains.json
  interval: 10m

routing:
  table: 1001
  rule:
    iif: br0
    priority: 1995
  route_timeout: 20m
